#!/usr/bin/env bash
#script use case statement
x="1"
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
		"4")echo "bad luck from China";;
		"9")echo "bad luck for Japan";;
		"17")echo "bad luck for Italy";;
	esac
	(( x++ ))
done
